# Generated by Django 2.1.7 on 2019-03-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0002_auto_20190228_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=''),
        ),
    ]
