# Generated by Django 2.1.7 on 2019-03-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0003_auto_20190228_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(default='1111, 11, 11'),
        ),
    ]
